
[font]
size = 12.0

[font.normal]
# family = "FixedsysModernV05 Nerd Font Mono"
# style = "Book"
family = "BigBlueTermPlus Nerd Font Mono"
style = "Regular"

[font.bold]
family = "BigBlueTermPlus Nerd Font Mono"
style = "Regular"

[general]
import = ["/home/connor/.config/alacritty/melange_dark.toml"]

[env]
TERM = "xterm"
