
[font]
size = 12.0

[font.normal]
#family = "UbuntuMono Nerd Font"
#style = "Regular"
family = "BigBlueTermPlus Nerd Font Mono"
style = "Regular"

[font.bold]
#family = "UbuntuMono Nerd Font"
#style = "Bold"
family = "BigBlueTermPlus Nerd Font Mono"
style = "Regular"

[general]
import = ["/home/connor/.config/alacritty/melange_dark.toml"]

[env]
TERM = "xterm"
